version: "1.0"
stages:
  - "clone"
  - "build"
  - "metadata"
  - "gitops"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "lrochette/gitops-app-source-code"
    revision: '${{CF_REVISION}}'
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "lrochette/argocd-my-app"
    working_directory: "${{clone}}"
    tags:
    - "latest"
    - '${{CF_SHORT_REVISION}}'
    dockerfile: "Dockerfile"
    stage: "build"
    registry: docker-lr
  enrich-image:
    title: Add PR info
    type: image-enricher
    stage: "metadata"
    arguments:
      IMAGE:  docker.io/lrochette/argocd-my-app:latest
      BRANCH: '${{CF_BRANCH}}'
      REPO: 'lrochette/gitops-app-source-code'
      GIT_PROVIDER_NAME: github
  jira-issue-extractor:
    title: Enrich image with jira issues
    type: jira-issue-extractor
    stage: "metadata"
    fail_fast: false
    arguments:
      IMAGE: docker.io/lrochette/argocd-my-app:latest
      JIRA_PROJECT_PREFIX: 'TAM'
      MESSAGE: TAM-1
      JIRA_HOST: codefresh-io.atlassian.net
      JIRA_EMAIL: laurent.rochette@codefresh.io
      JIRA_API_TOKEN: '${{JIRA_TOKEN}}'
  clone_gitops:
    title: cloning gitops repo
    type: git-clone
    arguments:
      repo: 'lrochette/gitops-kubernetes-configuration'
      revision: 'master'
    stage: "gitops"
    when:
      branch:
        only:
          - master
  change_manifest:
    title: "Update k8s manifest"
    image: "mikefarah/yq" # The image in which command will be executed
    commands:
      - yq w -i deployment.yml spec.template.spec.containers[0].image docker.io/lrochette/argocd-my-app:${{CF_SHORT_REVISION}}
      - cat deployment.yml
    working_directory: "${{clone_gitops}}"
    stage: "gitops"
    when:
      branch:
        only:
          - master
  commit_and_push:
    title: Commit manifest
    type: git-commit
    stage: "gitops"
    arguments:
      repo: 'lrochette/gitops-kubernetes-configuration'
      git: github
      working_directory: '/codefresh/volume/gitops-kubernetes-configuration'
      commit_message: Updated manifest
      git_user_name: lrochette
      git_user_email: laurent.rochette@codefresh.io
    when:
      branch:
        only:
          - master
  sync_and_wait:
    title: Sync ArgoCD app and wait
    type: argocd-sync
    arguments:
      context: argocd
      app_name: "${{ARGOCD_APP_NAME}}"
      wait_healthy: true
    stage: "gitops"
