version: "1.0"
stages:
  - "clone"
  - "build"
  - "metadata"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "lrochette/${{CF_REPO_NAME}}"
    revision: '${{CF_REVISION}}'
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "lrochette/argocd-my-app"
    working_directory: "${{clone}}"
    tags:
    - "latest"
    - '${{CF_SHORT_REVISION}}'
    dockerfile: "Dockerfile"
    stage: "build"
    registry: docker-lr
  enrich-image:
    title: Add PR info
    type: image-enricher
    stage: "metadata"
    arguments:
      IMAGE:  docker.io/lrochette/argocd-my-app:latest
      BRANCH: '${{CF_BRANCH}}'
      REPO: 'lrochette/${{CF_REPO_NAME}}'
      GIT_PROVIDER_NAME: github
  jira-issue-extractor:
    title: Enrich image with jira issues
    type: jira-issue-extractor
    stage: "metadata"
    fail_fast: false
    arguments:
      IMAGE: docker.io/lrochette/argocd-my-app:latest
      JIRA_PROJECT_PREFIX: 'TAM'
      MESSAGE: TAM-1
      JIRA_HOST: codefresh-io.atlassian.net
      JIRA_EMAIL: laurent.rochette@codefresh.io
      JIRA_API_TOKEN: '${{JIRA_TOKEN}}'
